model:
    multiscale:
        multiscale_input_channel: 3
        multiscale_output_channel: 1
    cross_attention:
        att_type: "soft_att"
    seq2vec:
        arch: skipthoughts
        dir_st: /root/autodl-tmp/zzc_backup/data/skipthoughts
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    embed:
        embed_dim: 512
    # decoder:
    #     final_conv_kernel: 1
    #     num_classes: 15
    VFM:
        sample: mean
        mapping: linear
    # SSA:
    #     weighting: linear
    #     downsample: averagePooling
    #     normalization: groupNorm
    name: IRSeg
dataset:
    datatype: rsicd
    # data_split: trainval
    data_split: all
    data_path: '/root/autodl-tmp/zzc_backup/code/private/SIRS/data/rsicd_precomp/'
    image_path: '/root/autodl-tmp/zzc_backup/data/RSICD/RSICD_images/'
    # seg_path: '/root/autodl-tmp/zzc_backup/data/RSITMD/mask/'
    vocab_path: '/root/autodl-tmp/zzc_backup/code/private/SIRS/data/vocab/rsicd_splits_vocab.json'
    batch_size: 128
    batch_size_val: 64
    train_workers: 4
    test_workers: 0
optim:
    epochs: 35
    lr: 0.0002
    lr_decay_param: 0.7
    lr_update_epoch: 20
    grad_clip: 0
    max_violation: 0
    margin: 0.2
    resume: False
    last_num_epochs_val: 10
    weight_save: False
    loss_weight:
        # SS: 80
        IR: 20
logs:
    eval_step: 1
    print_freq: 10
    ckpt_save_path: "/root/autodl-tmp/zzc_backup/archive/IRSeg_series/"
    logger_name: '/root/autodl-tmp/zzc_backup/archive/IRSeg_series/'
k_fold:
    experiment_name: 'rsicd_irseg_v1_noSeg'
    nums: 10
    current_num: 0