model:
    multiscale:
        multiscale_input_channel: 3
        multiscale_output_channel: 1
    cross_attention:
        att_type: "soft_att"
    seq2vec:
        arch: skipthoughts
        dir_st: /home/zzc/data/skipthoughts
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    embed:
        embed_dim: 512
    MIM:
        mask_ratio: 0.05
    VFM:
        sample: mean
        mapping: linear
    name: IRMIM
dataset:
    datatype: rsitmd
    data_split:
    data_path: 'data/rsitmd_precomp/'
    image_path: '/home/zzc/data/RSITMD/images/'
    vocab_path: 'data/vocab/rsitmd_splits_vocab.json'
    batch_size: 48
    batch_size_val: 32
    workers: 3
optim:
    epochs: 20
    lr: 0.0002
    lr_decay_param: 0.7
    lr_update_epoch: 20
    grad_clip: 0
    max_violation: 0
    margin: 0.2
    resume: False
    last_num_epochs_val: 10
    weight_save: False
logs:
    eval_step: 1
    print_freq: 10
    ckpt_save_path: "/home/zzc/archive/IRMIM_series/"
    logger_name: '/home/zzc/archive/IRMIM_series/'
k_fold:
    experiment_name: 'rsitmd_irmim_mr0.05'
    nums: 10
    current_num: 0
